### ISSUE TITLE
Pexpect missing as a requirement in the readme.

### ISSUE THREAD

**Issue by bergzand** [miri64/zep_mesh#1]
### Expected result:

Being able to run `zep_mesh_riot_native.py` with only networkx installed as a python dependency (and of course socat and netcat).

### Actual result:

```
(venv) hydrazine@gisteren ~/dev/zep_mesh $ ./zep_mesh_riot_native.py -n 5 -c 0.5
Traceback (most recent call last):
  File "./zep_mesh_riot_native.py", line 32, in <module>
    from app.riot_native import RIOTNativeApp
  File "/home/hydrazine/dev/zep_mesh/app/__init__.py", line 27, in <module>
    import app.riot_native
  File "/home/hydrazine/dev/zep_mesh/app/riot_native.py", line 27, in <module>
    import pexpect
ImportError: No module named 'pexpect'
```

### Proposed solution:

Adding pexpect to the dependency list

**Comment by bergzand** [comment]
~~mathplotlib~~ matplotlib is also missing from the dependency list

**Comment by miri64** [comment]
Done
